# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            omicro
tagline:          '球体型ロボット'
description:      'omicroはロボットボールです。スマートフォンやタブレットからbluetoothでつないで操作できます。Apple Watchを利用して複数のボールを同時に手の動きだけで操作することもできます。さらにUnityアプリから仮想の障害物をAR空間に設置して、現実のロボットボールを仮想障害物に当たらないように制御できます。'
url:              http://omicro.tokyo
baseurl:          http://omicro.tokyo

author:
  name:           'Takuya Ichise'
  url:            https://twitter.com/tichise

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/tichise/omicro

theme: jekyll-theme-cayman
