# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            omicro
tagline:          '自走球体型ロボット'
description:      'Self-propelled spherical robot ball made by <a href="https://twitter.com/tichise" target="_blank">Takuya Ichise</a>.'
url:              https://omicro.tokyo
baseurl:          https://omicro.tokyo/

author:
  name:           'Takuya Ichise'
  url:            https://twitter.com/tichise

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/tichise/omicro

theme: jekyll-theme-cayman
